// ============================================
// STATIC DATA - NO SUPABASE REQUIRED
// All data hardcoded from catalog PDF
// ============================================

import type { Category, Product, Review, Advantage } from './types';

// ============================================
// CATEGORIES
// ============================================
export const CATEGORIES: Category[] = [
  {
    id: 'cat-spetsiyi',
    name: 'Спеції',
    slug: 'spetsiyi',
    parent_id: null,
    image_url: '/images/categories/spices.jpg',
    sort_order: 1,
    is_visible: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'cat-pripravy',
    name: 'Приправи',
    slug: 'pripravy',
    parent_id: null,
    image_url: '/images/categories/seasonings.jpg',
    sort_order: 2,
    is_visible: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'cat-asorti',
    name: 'Овочеве асорті',
    slug: 'ovocheve-asorti',
    parent_id: null,
    image_url: '/images/categories/vegetables.jpg',
    sort_order: 3,
    is_visible: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'cat-makarony',
    name: 'Макарони',
    slug: 'makarony',
    parent_id: null,
    image_url: '/images/categories/pasta.jpg',
    sort_order: 4,
    is_visible: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'cat-konservy',
    name: 'Консервація',
    slug: 'konservatsiya',
    parent_id: null,
    image_url: '/images/categories/canned.jpg',
    sort_order: 5,
    is_visible: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'cat-oliya',
    name: 'Олія',
    slug: 'oliya',
    parent_id: null,
    image_url: '/images/categories/oil.jpg',
    sort_order: 6,
    is_visible: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
];

// ============================================
// PRODUCTS - From PDF catalog
// ============================================
export const PRODUCTS: Product[] = [
  // ============================================
  // СПЕЦІЇ (Перець, Паприка)
  // ============================================
  {
    id: 'prod-1',
    name: 'Перець чорний ГОРОШОК Преміум 200г',
    slug: 'perets-chornyi-goroshok-premium-200g',
    description: 'Перець чорний горошок преміум якість. Фасування 200г, 15шт в ящику.',
    category_id: 'cat-spetsiyi',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 1,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-2',
    name: 'Перець чорний МЕЛЕНИЙ Преміум 200г',
    slug: 'perets-chornyi-melenyi-premium-200g',
    description: 'Перець чорний мелений преміум якість. Фасування 200г, 15шт в ящику.',
    category_id: 'cat-spetsiyi',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 2,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-3',
    name: 'Перець чорний МЕЛЕНИЙ 1 ґатунок 200г',
    slug: 'perets-chornyi-melenyi-1gat-200g',
    description: 'Перець чорний мелений 1 ґатунок. Фасування 200г, 15шт в ящику.',
    category_id: 'cat-spetsiyi',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 3,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-4',
    name: 'Паприка червона 200г',
    slug: 'papryka-chervona-200g',
    description: 'Паприка червона солодка мелена. Фасування 200г, 15шт в ящику.',
    category_id: 'cat-spetsiyi',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 4,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-5',
    name: 'Паприка червона 100г',
    slug: 'papryka-chervona-100g',
    description: 'Паприка червона солодка мелена. Фасування 100г, 40шт в ящику.',
    category_id: 'cat-spetsiyi',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 5,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-6',
    name: 'Паприка КОПЧЕНА 200г',
    slug: 'papryka-kopchena-200g',
    description: 'Паприка червона копчена мелена. Фасування 200г, 20шт в ящику.',
    category_id: 'cat-spetsiyi',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 6,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-7',
    name: 'Паприка КОПЧЕНА 50г',
    slug: 'papryka-kopchena-50g',
    description: 'Паприка червона копчена мелена. Фасування 50г, 70шт в ящику.',
    category_id: 'cat-spetsiyi',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 7,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-8',
    name: 'Паприка ЧІЛІ гостра 50г',
    slug: 'papryka-chili-50g',
    description: 'Паприка чілі гостра мелена. Фасування 50г, 70шт в ящику.',
    category_id: 'cat-spetsiyi',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 8,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-9',
    name: 'Приправа Домашня з копченою паприкою 300г',
    slug: 'pryprava-domashnya-kopchena-300g',
    description: 'Набір приправ Домашня з копченою паприкою. Фасування 300г, 15шт в ящику.',
    category_id: 'cat-spetsiyi',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 9,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },

  // ============================================
  // ПРИПРАВИ (Універсальні набори, бакалія)
  // ============================================
  {
    id: 'prod-10',
    name: 'Приправа Універсальна 5кг (відро)',
    slug: 'pryprava-universalna-5kg-vidro',
    description: 'Універсальний набір приправ у пластиковому відрі. Фасування 5кг.',
    category_id: 'cat-pripravy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 1,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-11',
    name: 'Приправа Універсальна 1кг (відро)',
    slug: 'pryprava-universalna-1kg-vidro',
    description: 'Універсальний набір приправ у відрі. Фасування 1кг, 6шт в ящику.',
    category_id: 'cat-pripravy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 2,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-12',
    name: 'Приправа Універсальна 1кг (банка)',
    slug: 'pryprava-universalna-1kg-banka',
    description: 'Універсальний набір приправ у банці. Фасування 1кг, 12шт в ящику.',
    category_id: 'cat-pripravy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 3,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-13',
    name: 'Приправа Універсальна 600г (банка)',
    slug: 'pryprava-universalna-600g',
    description: 'Універсальний набір приправ у банці. Фасування 600г, 12шт в ящику.',
    category_id: 'cat-pripravy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 4,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-14',
    name: 'Приправа Універсальна 450г (банка)',
    slug: 'pryprava-universalna-450g',
    description: 'Універсальний набір приправ у банці. Фасування 450г, 15шт в ящику.',
    category_id: 'cat-pripravy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 5,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-15',
    name: 'Приправа Універсальна ПАЧКА 1кг',
    slug: 'pryprava-universalna-1kg-pachka',
    description: 'Універсальний набір приправ у пачці. Фасування 1кг, 12шт в ящику.',
    category_id: 'cat-pripravy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 6,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-16',
    name: 'Приправа Універсальна ПАЧКА 250г',
    slug: 'pryprava-universalna-250g-pachka',
    description: 'Універсальний набір приправ у пачці. Фасування 250г, 40шт в ящику.',
    category_id: 'cat-pripravy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 7,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-17',
    name: 'Гурманік для бульйонів та соусів 500г',
    slug: 'gurmanik-500g',
    description: 'Приправа для бульйонів та соусів. Фасування 500г, 12шт в ящику.',
    category_id: 'cat-pripravy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 8,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-18',
    name: 'Вігета 200г',
    slug: 'vigeta-200g',
    description: 'Приправа Вігета універсальна. Фасування 200г, 25шт в ящику.',
    category_id: 'cat-pripravy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 9,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-19',
    name: 'Лимонна кислота 350г',
    slug: 'lymonna-kyslota-350g',
    description: 'Лимонна кислота харчова. Фасування 350г, 15шт в ящику.',
    category_id: 'cat-pripravy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 10,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-20',
    name: 'Сода харчова 300г',
    slug: 'soda-300g',
    description: 'Сода харчова. Фасування 300г, 40шт в ящику.',
    category_id: 'cat-pripravy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 11,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },

  // ============================================
  // ОВОЧЕВЕ АСОРТІ (без солі та ароматизаторів)
  // ============================================
  {
    id: 'prod-21',
    name: 'Асорті овочеве 300г (банка)',
    slug: 'asorti-300g-banka',
    description: 'Овочеве асорті без солі та ароматизаторів у банці. Фасування 300г.',
    category_id: 'cat-asorti',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 1,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-22',
    name: 'Асорті овочеве 500г',
    slug: 'asorti-500g',
    description: 'Овочеве асорті без солі та ароматизаторів. Фасування 500г.',
    category_id: 'cat-asorti',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 2,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-23',
    name: 'Асорті овочеве 100г',
    slug: 'asorti-100g',
    description: 'Овочеве асорті без солі та ароматизаторів. Фасування 100г.',
    category_id: 'cat-asorti',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 3,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-24',
    name: 'Приправа до бульйону 100г',
    slug: 'do-bulyonu-100g',
    description: 'Овочева приправа до бульйону без солі та ароматизаторів. Фасування 100г.',
    category_id: 'cat-asorti',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 4,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-25',
    name: 'Приправа до голубців 100г',
    slug: 'do-golubtsiv-100g',
    description: 'Овочева приправа до голубців без солі та ароматизаторів. Фасування 100г.',
    category_id: 'cat-asorti',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 5,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-26',
    name: 'Приправа до рису 100г',
    slug: 'do-rysu-100g',
    description: 'Овочева приправа до рису без солі та ароматизаторів. Фасування 100г.',
    category_id: 'cat-asorti',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 6,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-27',
    name: 'Приправа до фасолі 100г',
    slug: 'do-fasoli-100g',
    description: 'Овочева приправа до фасолі без солі та ароматизаторів. Фасування 100г.',
    category_id: 'cat-asorti',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 7,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-28',
    name: 'Приправа до борщу 100г',
    slug: 'do-borshchu-100g',
    description: 'Овочева приправа до борщу без солі та ароматизаторів. Фасування 100г.',
    category_id: 'cat-asorti',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 8,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-29',
    name: 'Приправа до бограчу 100г',
    slug: 'do-bograchu-100g',
    description: 'Овочева приправа до бограчу без солі та ароматизаторів. Фасування 100г.',
    category_id: 'cat-asorti',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 9,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-30',
    name: 'Приправа для підлив та гуляша 100г',
    slug: 'dlya-pidlyv-gulyasha-100g',
    description: 'Овочева приправа для підлив та гуляша без солі та ароматизаторів. Фасування 100г.',
    category_id: 'cat-asorti',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 10,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-31',
    name: 'Приправа до шашлика 100г',
    slug: 'do-shashlyka-100g',
    description: 'Овочева приправа до шашлика без солі та ароматизаторів. Фасування 100г.',
    category_id: 'cat-asorti',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 11,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-32',
    name: '10 овочів 500г',
    slug: '10-ovochiv-500g',
    description: 'Суміш 10 овочів без солі та ароматизаторів. Фасування 500г.',
    category_id: 'cat-asorti',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 12,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-33',
    name: '10 овочів 100г',
    slug: '10-ovochiv-100g',
    description: 'Суміш 10 овочів без солі та ароматизаторів. Фасування 100г.',
    category_id: 'cat-asorti',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 13,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-34',
    name: 'Суміш зелені 100г',
    slug: 'sumish-zeleni-100g',
    description: 'Суміш сушеної зелені. Фасування 100г.',
    category_id: 'cat-asorti',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 14,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-35',
    name: 'Часник гранульований мелений 100г',
    slug: 'chasnyk-granulovanyi-100g',
    description: 'Часник гранульований мелений сушений. Фасування 100г.',
    category_id: 'cat-asorti',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 15,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-36',
    name: 'Часник мелений 100г',
    slug: 'chasnyk-melenyi-100g',
    description: 'Часник мелений сушений. Фасування 100г.',
    category_id: 'cat-asorti',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 16,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },

  // ============================================
  // МАКАРОНИ
  // ============================================
  {
    id: 'prod-37',
    name: 'Лапша коротка 3кг',
    slug: 'lapsha-korotka-3kg',
    description: 'Макаронні вироби "Лапша коротка". Фасування 3кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 1,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-38',
    name: 'Лапша коротка 1кг',
    slug: 'lapsha-korotka-1kg',
    description: 'Макаронні вироби "Лапша коротка". Фасування 1кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 2,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-39',
    name: 'Лапша довга 1кг',
    slug: 'lapsha-dovga-1kg',
    description: 'Макаронні вироби "Лапша довга". Фасування 1кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 3,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-40',
    name: 'Лапша 200г',
    slug: 'lapsha-200g',
    description: 'Макаронні вироби "Лапша". Фасування 200г.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 4,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-41',
    name: 'Кільця 3кг',
    slug: 'kiltsia-3kg',
    description: 'Макаронні вироби "Кільця". Фасування 3кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 5,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-42',
    name: 'Кільця 1кг',
    slug: 'kiltsia-1kg',
    description: 'Макаронні вироби "Кільця". Фасування 1кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 6,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-43',
    name: 'Зірочка 3кг',
    slug: 'zirochka-3kg',
    description: 'Макаронні вироби "Зірочка". Фасування 3кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 7,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-44',
    name: 'Зірочка 1кг',
    slug: 'zirochka-1kg',
    description: 'Макаронні вироби "Зірочка". Фасування 1кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 8,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-45',
    name: 'Ракушка 3кг',
    slug: 'rakushka-3kg',
    description: 'Макаронні вироби "Ракушка". Фасування 3кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 9,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-46',
    name: 'Ракушка 1кг',
    slug: 'rakushka-1kg',
    description: 'Макаронні вироби "Ракушка". Фасування 1кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 10,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-47',
    name: 'Перо коротке 3кг',
    slug: 'pero-korotke-3kg',
    description: 'Макаронні вироби "Перо коротке". Фасування 3кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 11,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-48',
    name: 'Перо коротке 1кг',
    slug: 'pero-korotke-1kg',
    description: 'Макаронні вироби "Перо коротке". Фасування 1кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 12,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-49',
    name: 'Перо довге 3кг',
    slug: 'pero-dovge-3kg',
    description: 'Макаронні вироби "Перо довге". Фасування 3кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 13,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-50',
    name: 'Перо довге 1кг',
    slug: 'pero-dovge-1kg',
    description: 'Макаронні вироби "Перо довге". Фасування 1кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 14,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-51',
    name: 'Рожка мала 3кг',
    slug: 'rozhka-mala-3kg',
    description: 'Макаронні вироби "Рожка мала". Фасування 3кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 15,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-52',
    name: 'Рожка мала 1кг',
    slug: 'rozhka-mala-1kg',
    description: 'Макаронні вироби "Рожка мала". Фасування 1кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 16,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-53',
    name: 'Рожка мала 500г',
    slug: 'rozhka-mala-500g',
    description: 'Макаронні вироби "Рожка мала". Фасування 500г.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 17,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-54',
    name: 'Рожка велика 3кг',
    slug: 'rozhka-velyka-3kg',
    description: 'Макаронні вироби "Рожка велика". Фасування 3кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 18,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-55',
    name: 'Рожка велика 1кг',
    slug: 'rozhka-velyka-1kg',
    description: 'Макаронні вироби "Рожка велика". Фасування 1кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 19,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-56',
    name: 'Рожка велика 500г',
    slug: 'rozhka-velyka-500g',
    description: 'Макаронні вироби "Рожка велика". Фасування 500г.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 20,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-57',
    name: 'Спіраль 3кг',
    slug: 'spiral-3kg',
    description: 'Макаронні вироби "Спіраль". Фасування 3кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 21,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-58',
    name: 'Спіраль 1кг',
    slug: 'spiral-1kg',
    description: 'Макаронні вироби "Спіраль". Фасування 1кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 22,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-59',
    name: 'Спіраль 500г',
    slug: 'spiral-500g',
    description: 'Макаронні вироби "Спіраль". Фасування 500г.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 23,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-60',
    name: 'Вермішель довга 1кг',
    slug: 'vermishel-dovga-1kg',
    description: 'Макаронні вироби "Вермішель довга". Фасування 1кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 24,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-61',
    name: 'Паутинка 3кг',
    slug: 'pautynka-3kg',
    description: 'Макаронні вироби "Паутинка". Фасування 3кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 25,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-62',
    name: 'Паутинка 1кг',
    slug: 'pautynka-1kg',
    description: 'Макаронні вироби "Паутинка". Фасування 1кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 26,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-63',
    name: 'Косичка 3кг',
    slug: 'kosychka-3kg',
    description: 'Макаронні вироби "Косичка". Фасування 3кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 27,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-64',
    name: 'Косичка 1кг',
    slug: 'kosychka-1kg',
    description: 'Макаронні вироби "Косичка". Фасування 1кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 28,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-65',
    name: 'Трубочка 3кг',
    slug: 'trubochka-3kg',
    description: 'Макаронні вироби "Трубочка". Фасування 3кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 29,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-66',
    name: 'Трубочка 1кг',
    slug: 'trubochka-1kg',
    description: 'Макаронні вироби "Трубочка". Фасування 1кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 30,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-67',
    name: 'Трубочка 500г',
    slug: 'trubochka-500g',
    description: 'Макаронні вироби "Трубочка". Фасування 500г.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 31,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-68',
    name: 'Галушка 3кг',
    slug: 'galushka-3kg',
    description: 'Макаронні вироби "Галушка". Фасування 3кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 32,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-69',
    name: 'Галушка 1кг',
    slug: 'galushka-1kg',
    description: 'Макаронні вироби "Галушка". Фасування 1кг.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 33,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-70',
    name: 'Галушка 500г',
    slug: 'galushka-500g',
    description: 'Макаронні вироби "Галушка". Фасування 500г.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 34,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-71',
    name: 'Локшина 200г',
    slug: 'lokshyna-200g',
    description: 'Макаронні вироби "Локшина". Фасування 200г.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 35,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-72',
    name: 'Чіга 200г',
    slug: 'chiga-200g',
    description: 'Макаронні вироби "Чіга". Фасування 200г.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 36,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-73',
    name: 'Торгоня 200г',
    slug: 'torgonya-200g',
    description: 'Макаронні вироби "Торгоня". Фасування 200г.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 37,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-74',
    name: 'Коцка 200г',
    slug: 'kotska-200g',
    description: 'Макаронні вироби "Коцка". Фасування 200г.',
    category_id: 'cat-makarony',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 38,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },

  // ============================================
  // КОНСЕРВАЦІЯ
  // ============================================
  {
    id: 'prod-75',
    name: 'Кукурудза консервована 420г',
    slug: 'kukurudza-420g',
    description: 'Кукурудза консервована ж/б. Фасування 420г, 12шт в ящику.',
    category_id: 'cat-konservy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 1,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-76',
    name: 'Горошок зелений консервований 420г',
    slug: 'goroshok-420g',
    description: 'Горошок зелений консервований ж/б. Фасування 420г, 12шт в ящику.',
    category_id: 'cat-konservy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 2,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-77',
    name: 'Огірки мариновані 720г',
    slug: 'ohirky-720g',
    description: 'Огірки мариновані консервовані. Фасування 720г, 6шт в ящику.',
    category_id: 'cat-konservy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 3,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-78',
    name: 'Огірки мариновані (твіст) 720г',
    slug: 'ohirky-tvist-720g',
    description: 'Огірки мариновані консервовані з твіст-кришкою. Фасування 720г, 8шт в упаковці.',
    category_id: 'cat-konservy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 4,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-79',
    name: 'Томати мариновані 720г',
    slug: 'tomaty-720g',
    description: 'Томати мариновані консервовані. Фасування 720г, 6шт в ящику.',
    category_id: 'cat-konservy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 5,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-80',
    name: 'Квасоля біла "Фірмова" 450г',
    slug: 'kvasolya-bila-firmova-450g',
    description: 'Квасоля біла консервована "Фірмова" с/б. Фасування 450г, 12шт в ящику.',
    category_id: 'cat-konservy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 6,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-81',
    name: 'Квасоля в томаті "Смачна" 450г',
    slug: 'kvasolya-v-tomati-smachna-450g',
    description: 'Квасоля в томатному соусі консервована "Смачна" с/б. Фасування 450г, 12шт в ящику.',
    category_id: 'cat-konservy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 7,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-82',
    name: 'Квасоля стручкова 720мл',
    slug: 'kvasolya-struchkova-720ml',
    description: 'Квасоля стручкова консервована. Фасування 720мл, 8шт в упаковці.',
    category_id: 'cat-konservy',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 8,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },

  // ============================================
  // ОЛІЯ
  // ============================================
  {
    id: 'prod-83',
    name: 'Олія соняшникова 5л',
    slug: 'oliya-5l',
    description: 'Олія соняшникова рафінована. Об\'єм 5л.',
    category_id: 'cat-oliya',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 1,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-84',
    name: 'Олія соняшникова 2л',
    slug: 'oliya-2l',
    description: 'Олія соняшникова рафінована. Об\'єм 2л.',
    category_id: 'cat-oliya',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: false,
    is_visible: true,
    sort_order: 2,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'prod-85',
    name: 'Олія соняшникова 1л',
    slug: 'oliya-1l',
    description: 'Олія соняшникова рафінована. Об\'єм 1л.',
    category_id: 'cat-oliya',
    price: null,
    old_price: null,
    unit: 'шт',
    min_order_qty: 1,
    image_url: null,
    images: [],
    in_stock: true,
    featured: true,
    is_visible: true,
    sort_order: 3,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
];

// ============================================
// REVIEWS
// ============================================
export const REVIEWS: Review[] = [
  {
    id: 'rev-1',
    author_name: 'Оксана М.',
    company: 'Продуктовий магазин',
    text: 'Замовляємо приправи та макарони регулярно. Ціни найкращі серед постачальників!',
    rating: 5,
    is_visible: true,
    sort_order: 1,
    created_at: '2024-01-01',
  },
  {
    id: 'rev-2',
    author_name: 'Андрій К.',
    company: 'Кафе "Смачна їжа"',
    text: 'Якісна продукція, швидка доставка. Особливо подобаються приправи.',
    rating: 5,
    is_visible: true,
    sort_order: 2,
    created_at: '2024-01-01',
  },
  {
    id: 'rev-3',
    author_name: 'Наталія П.',
    company: 'ФОП Наталія',
    text: 'Працюємо з Perfect 4 you вже півроку. Завжди все в наявності.',
    rating: 5,
    is_visible: true,
    sort_order: 3,
    created_at: '2024-01-01',
  },
];

// ============================================
// ADVANTAGES
// ============================================
export const ADVANTAGES: Advantage[] = [
  {
    id: 'adv-1',
    title: 'Працюємо без вихідних',
    description: 'Приймаємо замовлення 7 днів на тиждень',
    icon: 'clock',
    sort_order: 1,
    is_visible: true,
  },
  {
    id: 'adv-2',
    title: 'Доставка по Україні',
    description: 'Відправляємо замовлення по всій території',
    icon: 'truck',
    sort_order: 2,
    is_visible: true,
  },
  {
    id: 'adv-3',
    title: 'Великий асортимент',
    description: '80+ найменувань продукції',
    icon: 'package',
    sort_order: 3,
    is_visible: true,
  },
  {
    id: 'adv-4',
    title: 'Гнучкі умови',
    description: 'Зручна оплата після отримання',
    icon: 'credit-card',
    sort_order: 4,
    is_visible: true,
  },
];

// ============================================
// HELPER FUNCTIONS
// ============================================

export function getCategories(): Category[] {
  return CATEGORIES;
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find(c => c.slug === slug);
}

export function getProducts(): Product[] {
  return PRODUCTS;
}

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find(p => p.slug === slug);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return PRODUCTS.filter(p => p.category_id === categoryId);
}

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter(p => p.featured);
}

export function getRelatedProducts(productId: string, categoryId: string, limit = 4): Product[] {
  return PRODUCTS
    .filter(p => p.category_id === categoryId && p.id !== productId)
    .slice(0, limit);
}

export function getReviews(): Review[] {
  return REVIEWS;
}

export function getAdvantages(): Advantage[] {
  return ADVANTAGES;
}
